config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end
  def new
    @flat = Flat.new
  end
  def edit
    @flat = Flat.find(params[:id])
  end
  def update
    @flat = Flat.find(params[:id])
    if @flat.update(flats_params)
      redirect_to flats_path(@flat)
    else
      render :new
    end
  end
  def delete
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path
  end

  private
  def flats_params
    params.require(:flat).permit(:name, :address, :number_of_guests, :price_per_night, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class='container'>
  <h1>Edit flat <%=@flat.name%></h1>
  <%=simple_form_for(@flat) do |f|%>
  <% if @flat.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @flat.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.input :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.input :address, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.input :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.input :number_of_guests, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.input :price_per_night, class: "form-control" %>
    </div>
    <%= f.submit "Update", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/flats/index.html.erb
<div class='container'>
  <h1>All our Flats</h1>
    <div class="row">
      <% @flats.each do |flat|%>
      <div class="col-xs-6 col-md-4">
        <div class='card'>
          <div class='card-img' style="background-image: url('https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200')"></div>
          <div class='card-body'>
            <div class='card-name'><h3><%= flat.name %></h3></div>
            <div class='card-address'><p><%= flat.address %></p></div>
            <div class='flex'>
              <div class='icons'>
                <p><i class="fas fa-user-friends"></i><%= flat.number_of_guests %></p>
              </div>
              <div class='icons'>
                <p><i class="fas fa-euro-sign"></i><%= flat.price_per_night %></p>
              </div>
            </div>
          </div>
          <span class='card-footer'>
            <%=link_to "More info", class:'info'%>
            <%=link_to "Edit", edit_flat_path(flat), class:'edit'%>
            <%=link_to "Remove", class:'remove'%>
          </span>
        </div>
      </div>
      <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/new.html.erb
<div class='container'>
  <%simple_form_for(flat) do |f|%>
    <% if @restaurant.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
      </div>
    <% end %>
    <div class="form-group">
      <% f.label :name %>
      <% f.input :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <% f.label :address %>
      <% f.input :address, class: "form-control" %>
    </div>
    <div class="form-group">
      <% f.label :description %>
      <% f.input :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <% f.label :number_of_guests %>
      <% f.input :number_of_guests, class: "form-control" %>
    </div>
    <div class="form-group">
      <% f.label :price_per_night %>
      <% f.input :price_per_night, class: "form-control" %>
    </div>
    <%= f.submit "add a review", class: "btn btn-primary" %>
  <% end %>
</div>